### ISSUE TITLE
Game wont go past safety page

### ISSUE THREAD

**Issue by CloudySensei** [ckosmic/BeatSaber-AudioOutputDevice#1]
Whenever you load into Beat Saber, this is the only mod that stops the game from going past the Health and Safety page. After the screen just goes to a blank, black page

**Comment by Dashanesta** [comment]
I have the same issue, although it might because maybe I don't have the right dependencies or something.

**Comment by ckosmic** [comment]
Hi, this issue should be fixed if you redownload and reinstall the latest release.  This was a dumb mistake on my end where I put the wrong dll in the wrong place.
